export class CacheKeys {
  static readonly USER_INFO: string = 'user_info';
  static readonly USER_APPS: string = 'user_apps';
  static readonly USER_WALLPAPER: string = 'user_wallpaper';
  static readonly TOKEN: string = 'auth_token';
  static readonly REFRESH_TOKEN: string = 'refresh_token';
  static readonly P2P_LAST_PAIR_CODE: string = 'p2p_last_pair_code';
  static readonly DEVICE_FINGERPRINT_SEED: string = 'device_fingerprint_seed';
  static readonly VIDEO_PLAYER_DEVICE_ID: string = 'video_player_device_id';
  static readonly SAVED_SERVERS: string = 'saved_servers';
  static readonly LAST_SELECTED_SERVER: string = 'last_selected_server';
  static readonly AUTH_BASE_URL: string = 'auth_baseUrl';
  static readonly AUTH_SERVER_ID: string = 'auth_serverId';
  static readonly AUTH_ACCESS_TOKEN: string = 'auth_accessToken';
  static readonly AUTH_REFRESH_TOKEN: string = 'auth_refreshToken';
  static readonly AUTH_EXPIRES_IN: string = 'auth_expiresIn';
  static readonly AUTH_SHELL_SUPPORTED: string = 'auth_shellSupported';
  static readonly AUTH_SERVER_VERSION: string = 'auth_serverVersion';
  static readonly PRIVACY_CONSENT_ACCEPTED: string = 'privacy_consent_accepted';
}
