export class AppRouter {
  static readonly SERVER_LIST: string = 'ServerListPage';
  static readonly LOGIN: string = 'LoginPage';
  static readonly SERVER_ADD: string = 'ServerAddPage';
  static readonly ADMIN_CREATE: string = 'AdminCreatePage';
  static readonly RECOVER: string = 'RecoverPasswordPage';
  static readonly HOME: string = 'HomePage';
  static readonly SETTINGS: string = 'SettingsPage';
  static readonly LEGAL: string = 'LegalPage';
  static readonly FILES: string = 'FileBrowserPage';
  static readonly UPLOAD_CENTER: string = 'UploadCenterPage';
  static readonly PHOTO_TIMELINE: string = 'PhotoTimelinePage';
  static readonly PHOTO_MAIN: string = 'PhotoMainPage';
  static readonly PHOTO_TRASH: string = 'PhotoTrashPage';
  static readonly PHOTO_ALBUM_LIST: string = 'PhotoAlbumListPage';
  static readonly PHOTO_SMART_ALBUM_LIST: string = 'PhotoSmartAlbumListPage';
  static readonly PHOTO_COLLECTION_LIST: string = 'PhotoCollectionListPage';
  static readonly PHOTO_AI_FACES: string = 'PhotoAiFacesPage';
  static readonly PHOTO_AI_SCENES: string = 'PhotoAiScenesPage';
  static readonly PHOTO_AI_SIMILAR: string = 'PhotoAiSimilarPage';
  static readonly PHOTO_SETTINGS: string = 'PhotoSettingsPage';
}
