export class AppRouter {
  static readonly SERVER_LIST: string = 'ServerListPage';
  static readonly LOGIN: string = 'LoginPage';
  static readonly SERVER_ADD: string = 'ServerAddPage';
  static readonly ADMIN_CREATE: string = 'AdminCreatePage';
  static readonly RECOVER: string = 'RecoverPasswordPage';
  static readonly HOME: string = 'HomePage';
  static readonly SETTINGS: string = 'SettingsPage';
  static readonly LEGAL: string = 'LegalPage';
  static readonly FILES: string = 'FileBrowserPage';
}
